//------------------------------------------------------------------------------
// <auto-generated>
//     VSPackage 资源(与 .vsct 合并)。CTO 菜单资源由此提供。
// </auto-generated>
//------------------------------------------------------------------------------
namespace ClineVs.Package
{
	internal sealed partial class VSPackage { }
}
