namespace ZooVs.Package
{
	/// <summary>
	/// 深色主题变量(取自上游 webview-ui/.storybook/themes.ts 的 StorybookThemes.dark)。
	/// Cline 前端全部颜色来自 --vscode-* CSS 变量,宿主必须注入,否则界面视觉空白。
	/// </summary>
	internal static class WebviewTheme
	{
		public const string VarsJson = @"{""--vscode-editor-background"": ""#1E1E1E"",""--vscode-editor-foreground"": ""#D4D4D4"",""--vscode-sideBar-background"": ""#252526"",""--vscode-sideBar-foreground"": ""#CCCCCC"",""--vscode-editorGroup-border"": ""#454545"",""--vscode-descriptionForeground"": ""#CCCCCC99"",""--vscode-foreground"": ""#D4D4D4"",""--vscode-button-background"": ""#007ACC"",""--vscode-button-foreground"": ""#FFFFFF"",""--vscode-button-hoverBackground"": ""#005A9E"",""--vscode-button-separator"": ""#FFFFFF4D"",""--vscode-button-secondaryBackground"": ""#383B3D"",""--vscode-button-secondaryForeground"": ""#CCCCCC"",""--vscode-button-secondaryHoverBackground"": ""#454545"",""--vscode-textLink-foreground"": ""#6fc3df"",""--vscode-textLink-activeForeground"": ""#9CCBFF"",""--vscode-errorForeground"": ""#f48771"",""--vscode-editorWidget-border"": ""#303031"",""--vscode-editorError-foreground"": ""#f14c4c"",""--vscode-diffEditor-removedTextBackground"": ""#9c353520"",""--vscode-diffEditor-insertedTextBackground"": ""#9ccc6520"",""--vscode-editor-font-size"": ""12px"",""--vscode-font-size"": ""13px"",""--vscode-focusBorder"": ""#007ACC"",""--vscode-input-border"": ""#6B6B6B"",""--vscode-banner-background"": ""#007ACC"",""--vscode-banner-foreground"": ""#FFFFFF"",""--vscode-banner-iconForeground"": ""#FFFFFF"",""--vscode-titleBar-inactiveForeground"": ""#BBBBBB"",""--vscode-input-foreground"": ""#D4D4D4"",""--vscode-input-background"": ""#383B3D"",""--vscode-editor-line-height"": ""20px"",""--vscode-input-placeholderForeground"": ""#A6A6A6"",""--vscode-activityWarningBadge-background"": ""#F9C20B"",""--vscode-badge-background"": ""#007ACC"",""--vscode-badge-foreground"": ""#FFFFFF"",""--vscode-charts-green"": ""#73C991"",""--vscode-charts-yellow"": ""#F9C20B"",""--vscode-charts-red"": ""#F14C4C"",""--vscode-menu-background"": ""#252526"",""--vscode-menu-border"": ""#454545"",""--vscode-menu-foreground"": ""#CCCCCC"",""--vscode-menu-shadow"": ""#00000050"",""--vscode-menu-selectionBackground"": ""#062F4A"",""--vscode-menu-selectionForeground"": ""#FFFFFF"",""--vscode-inputValidation-errorBackground"": ""#eb1424"",""--vscode-inputValidation-errorForeground"": ""#fcd1c1"",""--vscode-editor-foldBackground"": ""#252526"",""--vscode-editor-foldPlaceholderForeground"": ""#454545"",""--vscode-list-activeSelectionBackground"": ""#094771"",""--vscode-list-activeSelectionForeground"": ""#FFFFFF"",""--vscode-list-hoverBackground"": ""#2D2D30"",""--vscode-editor-border"": ""#454545"",""--vscode-textCodeBlock-background"": ""#3E3E42"",""--vscode-toolbar-background"": ""#252526"",""--vscode-toolbar-hoverBackground"": ""#3E3E42"",""--vscode-widget-shadow"": ""#00000050"",""--vscode-panel-border"": ""#454545"",""--vscode-icon-foreground"": ""#CCCCCC"",""--vscode-problemsErrorIcon-foreground"": ""#be1100""}";
	}
}
